programa-principal: src/main.c
	gcc src/main.c src/query1.c src/randomfuncs.c src/structs.c src/age_time.c -Wall -o main `pkg-config --cflags --libs glib-2.0`

clean:
	rm -f programa-principal src/*.c